# These settings are synced to GitHub by https://github.com/github/safe-settings

repository:
  allow_auto_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_update_branch: true
  delete_branch_on_merge: true
  has_discussions: false
  has_downloads: false
  has_wiki: false
  squash_merge_commit_message: PR_BODY
  squash_merge_commit_title: PR_TITLE

teams:
  - name: mirsg
    permission: admin

# Each top-level element under branch protection must be filled. If one doesn't
# want to use one of them you must set it to empty. Otherwise, none of the
# settings will be applied.
branches:
  # `default` creates a branch protection rule to against the repo's base branch
  - name: default
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: false
        require_last_push_approval: false
        bypass_pull_request_allowances:
          apps:
            - renovate
          users: []
          teams: []
        dismissal_restrictions: {}
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      restrictions:
