name: Linting

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: UCL-MIRSG/.github/actions/linting@74b8380a4515702d37a8d0aff5e6411ddb4fd221 # v0.47.0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
