---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: UCL-MIRSG/.github/actions/linting@b863c874470757db8548388ab0135d573d70b48f # v0.127.0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
