---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: UCL-MIRSG/.github/actions/linting@561536e2ee67e89d148c1c9830c9debcf3a7ff07 # v0.69.0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
