---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: UCL-MIRSG/.github/actions/linting@c3814a70ce74e9b35fb361c4eeda033882314320 # v0.117.0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
