---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: UCL-MIRSG/.github/actions/linting@786c4954743c97b4d8f4d2ceeaf4c6c3348231d5 # v0.96.0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
