---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: UCL-MIRSG/.github/actions/linting@ecd8fdc4f0f39b826fb6d7e97922d66a9929308f # v0.107.0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
