name: Linting

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: UCL-MIRSG/.github/actions/linting@fa984de2f3f5eee75114b90fc721a96e57f33562 # v0.50.0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
